# Generated by Django 4.1.2 on 2022-10-14 06:10

from django.db import migrations, models
import problemsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('problemsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='img',
            field=models.ImageField(upload_to=problemsapp.models.upload_location),
        ),
    ]
